# Generated by Django 3.2.9 on 2021-12-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0002_user_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parts',
        ),
    ]
