# Generated by Django 3.2.9 on 2021-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0003_remove_user_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
