# Generated by Django 3.2.9 on 2021-12-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0004_user_model_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='model_categories',
            new_name='implements',
        ),
    ]
