# Generated by Django 3.2.9 on 2021-12-08 05:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0005_rename_model_categories_user_implements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, samples=None),
        ),
    ]
