# Generated by Django 3.2.9 on 2021-12-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0006_user_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
    ]
