# Generated by Django 3.2.9 on 2021-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0007_remove_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
