# Generated by Django 3.2.9 on 2021-12-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishifarm', '0008_user_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='model_number',
        ),
    ]
